# golangci-lint configuration
# Only lints that are critical for production code

# Version 2 config format (required for local golangci-lint v2)
# Note: GitHub Actions uses golangci-lint-action which doesn't require this
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - unused
  disable:
    - errcheck     # Too many pre-existing issues
    - staticcheck  # Too many style suggestions
    - goconst      # Too noisy for test files
    - gocognit     # Complex test functions are acceptable
    - gocyclo      # Complex test functions are acceptable

linters-settings:
  errcheck:
    check-blank: false  # Allow error assignment to _
    exclude-functions:
      # Allow ignoring errors in test code for brevity
      - (io.Closer).Close
      - (*os.File).Close
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
      - fmt.Fprintln
      - fmt.Fprintf
      - os.RemoveAll
      - os.Unsetenv
      - os.Setenv
  staticcheck:
    checks:
      - "all"
      - "-QF1001"  # De Morgan's law - code clarity preference
      - "-QF1003"  # Tagged switch - code clarity preference
      - "-ST1005"  # Error capitalization - pre-existing style
  goconst:
    min-occurrences: 5  # Require at least 5 occurrences before flagging
  gocognit:
    min-complexity: 30  # Allow complex test setup functions
  gocyclo:
    min-complexity: 20  # Allow moderately complex functions
  govet:
    disable:
      - fieldalignment  # Struct optimization not critical for correctness

issues:
  exclude-rules:
    # Disable err check for test files - tests often use _ for brevity
    - path: _test\.go
      linters:
        - errcheck
    # Disable shadow checks for test files - common pattern in table tests
    - path: _test\.go
      linters:
        - govet
      text: "shadow:"
    # Disable fieldalignment for test structs
    - path: _test\.go
      linters:
        - govet
      text: "fieldalignment:"
    # Disable goconst for test files - hardcoded strings are common
    - path: _test\.go
      linters:
        - goconst
    # Disable staticcheck quickfix suggestions (QF codes)
    - linters:
        - staticcheck
      text: "QF"
    # Disable staticcheck style suggestions (ST codes)
    - linters:
        - staticcheck
      text: "ST1005"
  max-same-issues: 0
  max-issues-per-linter: 0
