# golangci-lint configuration
# Only lints that are critical for production code

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocognit
    - gocyclo

linters-settings:
  errcheck:
    exclude-functions:
      # Allow ignoring errors in test code for brevity
      - (io.Closer).Close
      - (*os.File).Close
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
  goconst:
    min-occurrences: 5  # Require at least 5 occurrences before flagging
  gocognit:
    min-complexity: 30  # Allow complex test setup functions
  gocyclo:
    min-complexity: 20  # Allow moderately complex functions
  govet:
    enable:
      - fieldalignment
    fieldalignment:
      suggest-new: true

issues:
  exclude-rules:
    # Disable err check for test files - tests often use _ for brevity
    - path: _test\.go
      linters:
        - errcheck
    # Disable shadow checks for test files - common pattern in table tests
    - path: _test\.go
      linters:
        - govet
      text: "shadow:"
    # Disable fieldalignment for test structs
    - path: _test\.go
      linters:
        - govet
      text: "fieldalignment:"
    # Disable goconst for test files - hardcoded strings are common
    - path: _test\.go
      linters:
        - goconst
  max-same-issues: 0
  max-issues-per-linter: 0
