name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Version
      description: meta-cc version (run `meta-cc --version`)
      placeholder: "v0.11.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions
      placeholder: |
        1. Run command '''...'''
        2. Observe error '''...'''
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Go version, etc.
      placeholder: |
        - OS: Ubuntu 22.04
        - Go: 1.21
    validations:
      required: true
