name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          # Primary development target
          - os: ubuntu-latest
            go: '1.24'
          # Mac users matter (most Claude Code users)
          - os: macos-latest
            go: '1.24'
          # Backward compatibility check
          - os: ubuntu-latest
            go: '1.23'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for CHANGELOG validation

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Record test start time
        id: test_start
        shell: bash
        run: echo "TEST_START=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Verify plugin file sync
        shell: bash
        run: |
          bash scripts/sync-plugin-files.sh
          bash scripts/sync-plugin-files.sh --verify

      - name: Check CHANGELOG updated
        if: github.event_name == 'pull_request'
        shell: bash
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          bash scripts/ci/check-changelog-updated.sh

      - name: Run tests
        run: make test

      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        run: make test-coverage

      - name: Cache golangci-lint
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-golangci-

      - name: Run linter
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        run: make lint

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella

      - name: Check coverage threshold
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        shell: bash
        run: bash scripts/checks/check-coverage.sh 75

      - name: Calculate test duration
        if: always() && matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        shell: bash
        run: |
          START=${{ steps.test_start.outputs.TEST_START }}
          END=$(date +%s)
          DURATION=$((END - START))
          echo "⏱️  Test suite completed in ${DURATION} seconds"
          echo "TEST_DURATION=${DURATION}" >> $GITHUB_ENV

      - name: Track test duration metric
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24'
        shell: bash
        run: |
          bash scripts/ci/track-metrics.sh test_duration ${{ env.TEST_DURATION }} seconds

      - name: Check performance regression
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24' && github.event_name == 'pull_request'
        shell: bash
        run: |
          # Check test duration regression (20% threshold)
          # Exit code 2 (insufficient data) is treated as a warning, not a failure
          bash scripts/ci/check-performance-regression.sh test_duration ${{ env.TEST_DURATION }} 20 || [ $? -eq 2 ]

      - name: Commit and push metrics
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.24' && github.event_name == 'push'
        shell: bash
        run: |
          # Configure git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Check if metrics changed
          if ! git diff --quiet .ci-metrics/; then
            git add .ci-metrics/
            git commit -m "ci: update performance metrics [skip ci]"
            git push
          else
            echo "No metrics changes to commit"
          fi

  pipeline-tests:
    name: Pipeline Script Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for CHANGELOG validation

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run Bats tests
        run: |
          bats tests/scripts/*.bats

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for CHANGELOG validation

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
