name: Error Linting

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  lint-errors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run error linter
        run: |
          chmod +x scripts/lint-errors.sh
          make lint-errors

      - name: Report status
        if: success()
        run: echo "✓ All error conventions validated"
